services:
  app:
    build:
      context: .
      dockerfile: ./src/app/Dockerfile
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nodemon src/app/index.ts
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/launcher_tracker
      dockerfile: Dockerfile
    volumes:
      - ./frontend/launcher_tracker:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: npm run serve
    networks:
      - app-network

networks:
  app-network: