services:
  app:
    build:
      context: .
      dockerfile: ./src/app/Dockerfile
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nodemon src/app/index.ts
